(() => {
  const clamp = (value, min = 0, max = 1) => Math.min(max, Math.max(min, value));
  const reducedMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  const header = document.querySelector('[data-header]');
  const navToggle = document.querySelector('[data-nav-toggle]');
  const nav = document.querySelector('[data-nav]');
  navToggle?.addEventListener('click', () => { const open = navToggle.getAttribute('aria-expanded') !== 'true'; navToggle.setAttribute('aria-expanded', String(open)); nav?.classList.toggle('is-open', open); });
  nav?.querySelectorAll('a').forEach((link) => link.addEventListener('click', () => { navToggle?.setAttribute('aria-expanded', 'false'); nav?.classList.remove('is-open'); }));
  const story = document.querySelector('[data-story]'); const progressBar = document.querySelector('[data-progress]'); const storyIndex = document.querySelector('[data-story-index]'); const exploded = document.querySelector('[data-exploded]'); const storyCopies = [...document.querySelectorAll('[data-copy]')]; const sequenceCanvas = document.querySelector('[data-gauge-sequence]'); const sequenceContext = sequenceCanvas?.getContext('2d');
  const sequenceImages = Array.from({ length: 25 }, (_, index) => { const image = new Image(); image.src = `assets/metrik/frame-${String(index).padStart(3, '0')}.png`; return image; }); let lastFrame = -1;
  const drawGaugeFrame = (frame) => { if (!sequenceCanvas || !sequenceContext) return; const image = sequenceImages[frame]; if (!image?.complete || !image.naturalWidth) return; sequenceContext.clearRect(0, 0, sequenceCanvas.width, sequenceCanvas.height); sequenceContext.drawImage(image, 0, 0, sequenceCanvas.width, sequenceCanvas.height); sequenceCanvas.classList.add('is-ready'); };
  sequenceImages.forEach((image, index) => image.addEventListener('load', () => { if (index === 0 && lastFrame === -1) drawGaugeFrame(0); }, { once: true }));
  const updateStory = () => { const scrollY = window.scrollY; header?.classList.toggle('is-scrolled', scrollY > 20); if (!story) return; const range = Math.max(1, story.offsetHeight - window.innerHeight); const progress = clamp((scrollY - story.offsetTop) / range); const assembly = clamp(progress / .23); const rotation = clamp((progress - .14) / .72); progressBar?.style.setProperty('height', `${progress * 100}%`); if (storyIndex) storyIndex.textContent = `${String(Math.min(4, Math.floor(progress * 4) + 1)).padStart(2, '0')} / 04`; if (exploded) { const distance = 1 - assembly; exploded.style.setProperty('--front-x', `${28 * distance}vw`); exploded.style.setProperty('--shell-x', `${28 * distance}vw`); exploded.style.setProperty('--core-y', `${7 * distance}vw`); exploded.style.opacity = String(1 - clamp((assembly - .64) / .36)); } storyCopies.forEach((copy) => { const start = Number(copy.dataset.start); const end = Number(copy.dataset.end); const local = clamp((progress - start) / (end - start)); const opacity = Math.min(1, local * 4, (1 - local) * 4); copy.style.opacity = String(opacity); copy.style.transform = `translateY(${(1 - opacity) * 22}px)`; }); const frame = Math.round(rotation * (sequenceImages.length - 1)); if (frame !== lastFrame) { lastFrame = frame; drawGaugeFrame(frame); } document.querySelector('[data-scroll-cue]')?.style.setProperty('opacity', String(1 - clamp(progress * 6))); };
  let scrollQueued = false; window.addEventListener('scroll', () => { if (scrollQueued) return; scrollQueued = true; requestAnimationFrame(() => { updateStory(); scrollQueued = false; }); }, { passive: true }); window.addEventListener('resize', updateStory); updateStory();
  const revealGroup = document.querySelector('[data-reveal-group]'); if (revealGroup && 'IntersectionObserver' in window) { new IntersectionObserver((entries, observer) => { if (!entries[0].isIntersecting) return; revealGroup.classList.add('is-visible'); observer.disconnect(); }, { threshold: .2 }).observe(revealGroup); } else { revealGroup?.classList.add('is-visible'); }
  const dial = document.querySelector('[data-demo-dial]'); const dialContext = dial?.getContext('2d'); const themes = { signal:{background:'#061e35',primary:'#58d7ff',accent:'#ff4b20',secondary:'#a7efff'}, race:{background:'#1a1517',primary:'#ff5d45',accent:'#ffba4d',secondary:'#ffe3d2'}, night:{background:'#100e1d',primary:'#b69aff',accent:'#6edcff',secondary:'#e5dcff'} }; let currentTheme = 'signal'; let startTime = performance.now();
  const drawDial = (now) => { if (!dial || !dialContext) return; const ctx = dialContext; const theme = themes[currentTheme]; const size = dial.width; const center = size / 2; const radius = size * .47; const phase = reducedMotion ? .64 : ((Math.sin((now - startTime) / 1300) + 1) / 2) * .82 + .09; ctx.clearRect(0, 0, size, size); ctx.fillStyle = theme.background; ctx.beginPath(); ctx.arc(center, center, radius, 0, Math.PI * 2); ctx.fill(); ctx.lineWidth = 5; ctx.strokeStyle = `${theme.primary}66`; ctx.beginPath(); ctx.arc(center, center, radius * .93, 0, Math.PI * 2); ctx.stroke(); for (let index = 0; index <= 12; index += 1) { const angle = Math.PI * (1.17 + index / 12 * 1.66); const outer = radius * .86; const inner = outer - (index % 3 === 0 ? 24 : 13); ctx.lineWidth = index % 3 === 0 ? 7 : 3; ctx.strokeStyle = theme.primary; ctx.beginPath(); ctx.moveTo(center + Math.cos(angle) * outer, center + Math.sin(angle) * outer); ctx.lineTo(center + Math.cos(angle) * inner, center + Math.sin(angle) * inner); ctx.stroke(); } ctx.fillStyle = theme.secondary; ctx.font = '700 92px "Space Grotesk", sans-serif'; ctx.textAlign = 'center'; ctx.fillText(String(Math.round(phase * 100)).padStart(2, '0'), center, center + 29); ctx.font = '500 19px "DM Mono", monospace'; ctx.fillStyle = theme.primary; ctx.fillText('METRIK / DEMO', center, center + 63); const angle = Math.PI * (1.17 + phase * 1.66); ctx.strokeStyle = theme.accent; ctx.lineWidth = 11; ctx.lineCap = 'round'; ctx.beginPath(); ctx.moveTo(center, center); ctx.lineTo(center + Math.cos(angle) * radius * .72, center + Math.sin(angle) * radius * .72); ctx.stroke(); ctx.fillStyle = theme.accent; ctx.beginPath(); ctx.arc(center, center, 20, 0, Math.PI * 2); ctx.fill(); if (!reducedMotion) requestAnimationFrame(drawDial); };
  if (dialContext) requestAnimationFrame(drawDial); document.querySelectorAll('[data-theme]').forEach((button) => button.addEventListener('click', () => { currentTheme = button.dataset.theme; startTime = performance.now(); document.querySelectorAll('[data-theme]').forEach((choice) => choice.classList.toggle('is-active', choice === button)); if (reducedMotion) drawDial(startTime); }));
})();
